project:
  type: website

website:
  title: "Once Upon A Time Series"
  navbar:
      left:
      - about.qmd
      right:
      - icon: linkedin
        href: https://linkedin.com/in/lgibson7
      - icon: github
        href: https://github.com/lgibson7
      - icon: twitter
        href: https://twitter.com/Lydz_is_Poppin
      
format:
  html:
    theme: vapor
    css: styles.css

